schemas:
  bootstrap: 8000
  custom: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://test/themes/bootstrap/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://IMG9915.JPG'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
